### ISSUE TITLE
Failed to build marblerun on ubuntu 20.04

### ISSUE THREAD

**Issue by Glenrun** [edgelesssys/marblerun#295]
### Issue description
Failed to build marblerun on ubuntu 20.04
### To reproduce

1.wget https://github.com/edgelesssys/marblerun/archive/refs/tags/v0.5.1.tar.gz
2.cd marblerun-0.5.1
3. mkdir build; cd build; cmake ..; make

### Expected behavior

Build should succeed
### Environment:
 - MarbleRun version:0.5.1
 - Edgeless RT version: latest
 - Go version:1.18.2
 - Minikube version:no use

**Comment by m1ghtym0** [comment]
Hi @Glenrun,

Did you make sure you have our prerequisites installed?
```
* [Edgeless RT](https://github.com/edgelesssys/edgelessrt) is installed and sourced
* Go 1.14 or newer
```

Can you give us the error message / build output? 

Thanks

**Comment by LouisCaixuran** [comment]
I have the same problem and I have ensured that I met all the prerequisites. The errors happened when in process Linking CXX executable coordinator-enclave

**Comment by m1ghtym0** [comment]
Hi @LouisCaixuran,
Can you give us the error output of the linker?

**Comment by LouisCaixuran** [comment]
the error output is long and the first lines of it is 

```
/usr/bin/ld: /usr/lib/gcc/x86_64-linux-gnu/11/libstdc++.a(guard.o): in function `__cxa_guard_acquire':
(.text.__cxa_guard_acquire+0x17): undefined reference to `__libc_single_threaded'
/usr/bin/ld: /usr/lib/gcc/x86_64-linux-gnu/11/libstdc++.a(guard.o): in function `__cxa_guard_abort':
(.text.__cxa_guard_abort+0x7): undefined reference to `__libc_single_threaded'
.....
```

**Comment by m1ghtym0** [comment]
Thanks, can you also give me the following information on your build environment:
* gcc version
* libc version
* OS 
* golang version

**Comment by LouisCaixuran** [comment]
gcc version 11.2.0
libc version ldd (Ubuntu GLIBC 2.35-0ubuntu3) 2.35
OS Ubuntu 22.04 LTS
golang 1.18.1

**Comment by daniel-weisse** [comment]
Ubuntu 22.04 is not yet supported as the SGX libraries we build on only support Ubuntu 16.04, 18.04 and 20.04.
If you wish to build on newer releases, I would recommend doing so in a Docker container with an Ubuntu 20.04 image.

**Comment by m1ghtym0** [comment]
@LouisCaixuran Were you able to build it on Ubuntu 20.04.?

**Comment by LouisCaixuran** [comment]
sorry for the late update. It works successfully on Ubuntu20.04

**Comment by m1ghtym0** [comment]
No worries, glad it works!:-)
